### ISSUE TITLE
关于login的api问题

### ISSUE THREAD

**Issue by Err0rCM** [ShirasawaSama/auto-sust-yiban-infoupload#2]
感谢大佬的无偿分享！今天发现更新无法登陆了，正在搜索发现大佬已经分析完了。
想问一下登陆的api：/api/v4/passport/login
POST参数：mobile=xxx&password=xxx&ct=1&identify=x
想请教下ct和identify的具体含义，以及为什么这些必须参数提交后仍提示版本过低的问题呢？

**Comment by Err0rCM** [comment]
感谢大佬百忙之中抽空回答！
目前ct和identify已经确认，但是仍提示客户端版本过低
```
{
'Origin': 'https://mobile.yiban.cn', 
'User-Agent': 'YiBan/5.0 Mozilla/5.0 (Linux; Android 7.1.2; V1938T Build/N2G48C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Safari/537.36', 
'Referer': 'https://mobile.yiban.cn',
 'AppVersion': '5.0'
}
您的客户端版本太低，请到易班官网下载最新版本[2]
```
这是我的请求header(python dict格式)，下方是请求返回的message，唯一不同的是最后的这个[1]变成了[2]，不清楚含义。
想请教下大佬是否在开发过程中遇到了这个问题，是如何解决的呢？

**Comment by Mashiro2000** [comment]
> 感谢大佬百忙之中抽空回答！
> 目前ct和identify已经确认，但是仍提示客户端版本过低
> 
> ```
> {
> 'Origin': 'https://mobile.yiban.cn', 
> 'User-Agent': 'YiBan/5.0 Mozilla/5.0 (Linux; Android 7.1.2; V1938T Build/N2G48C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Safari/537.36', 
> 'Referer': 'https://mobile.yiban.cn',
>  'AppVersion': '5.0'
> }
> 您的客户端版本太低，请到易班官网下载最新版本[2]
> ```
> 
> 这是我的请求header(python dict格式)，下方是请求返回的message，唯一不同的是最后的这个[1]变成了[2]，不清楚含义。
> 想请教下大佬是否在开发过程中遇到了这个问题，是如何解决的呢？

我也是这样

**Comment by Mashiro2000** [comment]
> 感谢大佬百忙之中抽空回答！
> 目前ct和identify已经确认，但是仍提示客户端版本过低
> 
> ```
> {
> 'Origin': 'https://mobile.yiban.cn', 
> 'User-Agent': 'YiBan/5.0 Mozilla/5.0 (Linux; Android 7.1.2; V1938T Build/N2G48C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Safari/537.36', 
> 'Referer': 'https://mobile.yiban.cn',
>  'AppVersion': '5.0'
> }
> 您的客户端版本太低，请到易班官网下载最新版本[2]
> ```
> 
> 这是我的请求header(python dict格式)，下方是请求返回的message，唯一不同的是最后的这个[1]变成了[2]，不清楚含义。
> 想请教下大佬是否在开发过程中遇到了这个问题，是如何解决的呢？

getIMEI(mobile)这个函数你是如何改写成适合python的呢

**Comment by ShirasawaSama** [comment]
@Err0rCM `[2]` 我如果没记错的话，应该是password解密失败

使用的加密算法应当是 `Rsa/None/Pkcs1padding`

**Comment by ShirasawaSama** [comment]
@Mashiro2000 这个值其实可以随便填，说是手机的iemi，但是填0或其他数字也能正常登陆。

我这里是写了个根据手机号生成固定iemi的算法，你用其他的算法来构造也可以，直接用真的iemi然后固定死也可以

**Comment by Mashiro2000** [comment]
> @Mashiro2000 这个值其实可以随便填，说是手机的iemi，但是填0或其他数字也能正常登陆。
> 
> 我这里是写了个根据手机号生成固定iemi的算法，你用其他的算法来构造也可以，直接用真的iemi然后固定死也可以

谢谢，

**Comment by Mashiro2000** [comment]
> @Err0rCM `[2]` 我如果没记错的话，应该是password解密失败
> 
> 使用的加密算法应当是 `Rsa/None/Pkcs1padding`
> 
> _另外 `ct ` 的含义我也想了解一下_

请问下，大佬，你们现在是使用什么进行抓包，mumu模拟器好像已经不行了

**Comment by Err0rCM** [comment]
> > 感谢大佬百忙之中抽空回答！
> > 目前ct和identify已经确认，但是仍提示客户端版本过低
> > ```
> > {
> > 'Origin': 'https://mobile.yiban.cn', 
> > 'User-Agent': 'YiBan/5.0 Mozilla/5.0 (Linux; Android 7.1.2; V1938T Build/N2G48C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Safari/537.36', 
> > 'Referer': 'https://mobile.yiban.cn',
> >  'AppVersion': '5.0'
> > }
> > 您的客户端版本太低，请到易班官网下载最新版本[2]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这是我的请求header(python dict格式)，下方是请求返回的message，唯一不同的是最后的这个[1]变成了[2]，不清楚含义。
> > 想请教下大佬是否在开发过程中遇到了这个问题，是如何解决的呢？
> 
> getIMEI(mobile)这个函数你是如何改写成适合python的呢

```python
def luhn_residue(digits):
    sum = 0
    for i in digits:
        sum += int(i)
    return digits+str(sum//10)

def getImei(N):
    SumDigits = ""
    for i in N:
        i = int(i)
        digit2 = 0
        if i % 2 == 0:
            Multipliers = 2
        else:
            Multipliers = 1
        digit = i*Multipliers
        for j in str(digit):
            digit2 = int(j)
        SumDigits += str(digit2)
    N = luhn_residue(N)
    return N

print(getImei("7992739871"))
```
这个可以参考一下，不过登陆不验证iemi
我是参考维基百科 https://en.wikipedia.org/wiki/Luhn_algorithm

**Comment by Mashiro2000** [comment]
> > > 感谢大佬百忙之中抽空回答！
> > > 目前ct和identify已经确认，但是仍提示客户端版本过低
> > > ```
> > > {
> > > 'Origin': 'https://mobile.yiban.cn', 
> > > 'User-Agent': 'YiBan/5.0 Mozilla/5.0 (Linux; Android 7.1.2; V1938T Build/N2G48C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Safari/537.36', 
> > > 'Referer': 'https://mobile.yiban.cn',
> > >  'AppVersion': '5.0'
> > > }
> > > 您的客户端版本太低，请到易班官网下载最新版本[2]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这是我的请求header(python dict格式)，下方是请求返回的message，唯一不同的是最后的这个[1]变成了[2]，不清楚含义。
> > > 想请教下大佬是否在开发过程中遇到了这个问题，是如何解决的呢？
> > 
> > 
> > getIMEI(mobile)这个函数你是如何改写成适合python的呢
> 
> ```python
> def luhn_residue(digits):
>     sum = 0
>     for i in digits:
>         sum += int(i)
>     return digits+str(sum//10)
> 
> def getImei(N):
>     SumDigits = ""
>     for i in N:
>         i = int(i)
>         digit2 = 0
>         if i % 2 == 0:
>             Multipliers = 2
>         else:
>             Multipliers = 1
>         digit = i*Multipliers
>         for j in str(digit):
>             digit2 = int(j)
>         SumDigits += str(digit2)
>     N = luhn_residue(N)
>     return N
> 
> print(getImei("7992739871"))
> ```
> 
> 这个可以参考一下，不过登陆不验证iemi
> 我是参考维基百科 https://en.wikipedia.org/wiki/Luhn_algorithm

嗯，了解，你现在可以登录了吗，我还是返回2

**Comment by Err0rCM** [comment]
> > > > 感谢大佬百忙之中抽空回答！
> > > > 目前ct和identify已经确认，但是仍提示客户端版本过低
> > > > ```
> > > > {
> > > > 'Origin': 'https://mobile.yiban.cn', 
> > > > 'User-Agent': 'YiBan/5.0 Mozilla/5.0 (Linux; Android 7.1.2; V1938T Build/N2G48C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Safari/537.36', 
> > > > 'Referer': 'https://mobile.yiban.cn',
> > > >  'AppVersion': '5.0'
> > > > }
> > > > 您的客户端版本太低，请到易班官网下载最新版本[2]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 这是我的请求header(python dict格式)，下方是请求返回的message，唯一不同的是最后的这个[1]变成了[2]，不清楚含义。
> > > > 想请教下大佬是否在开发过程中遇到了这个问题，是如何解决的呢？
> > > 
> > > 
> > > getIMEI(mobile)这个函数你是如何改写成适合python的呢
> > 
> > 
> > ```python
> > def luhn_residue(digits):
> >     sum = 0
> >     for i in digits:
> >         sum += int(i)
> >     return digits+str(sum//10)
> > 
> > def getImei(N):
> >     SumDigits = ""
> >     for i in N:
> >         i = int(i)
> >         digit2 = 0
> >         if i % 2 == 0:
> >             Multipliers = 2
> >         else:
> >             Multipliers = 1
> >         digit = i*Multipliers
> >         for j in str(digit):
> >             digit2 = int(j)
> >         SumDigits += str(digit2)
> >     N = luhn_residue(N)
> >     return N
> > 
> > print(getImei("7992739871"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个可以参考一下，不过登陆不验证iemi
> > 我是参考维基百科 https://en.wikipedia.org/wiki/Luhn_algorithm
> 
> 嗯，了解，你现在可以登录了吗，我还是返回2

还是不行，根据作者大佬的说法，可能是它api对password解密失败导致的。如果真是这样的话 这里得去请教下密码师傅了

**Comment by Err0rCM** [comment]
> @Err0rCM `[2]` 我如果没记错的话，应该是password解密失败
> 
> 使用的加密算法应当是 `Rsa/None/Pkcs1padding`
> 
> _另外 `ct ` 的含义我也想了解一下_

明白了，看来重构成python必须要找到对应的加密方式，请问师傅的代码可以正确登陆吗？

`ct`的含义其实并不明显，我也不知道具体的含义，记得在之前一个yiban项目看到过，没有什么大的影响似乎。

**Comment by Mashiro2000** [comment]
> > @Err0rCM `[2]` 我如果没记错的话，应该是password解密失败
> > 使用的加密算法应当是 `Rsa/None/Pkcs1padding`
> > _另外 `ct ` 的含义我也想了解一下_
> 
> 明白了，看来重构成python必须要找到对应的加密方式，请问师傅的代码可以正确登陆吗？
> 
> `ct`的含义其实并不明显，我也不知道具体的含义，记得在之前一个yiban项目看到过，没有什么大的影响似乎。

好兄弟，你成功了吗，我网上找python版本的Rsa/None/Pkcs1padding，没找到，晚上回去再试试看了

**Comment by Err0rCM** [comment]
> > > @Err0rCM `[2]` 我如果没记错的话，应该是password解密失败
> 
> > > 使用的加密算法应当是 `Rsa/None/Pkcs1padding`
> 
> > > _另外 `ct ` 的含义我也想了解一下_
> 
> > 
> 
> > 明白了，看来重构成python必须要找到对应的加密方式，请问师傅的代码可以正确登陆吗？
> 
> > 
> 
> > `ct`的含义其实并不明显，我也不知道具体的含义，记得在之前一个yiban项目看到过，没有什么大的影响似乎。
> 
> 
> 
> 好兄弟，你成功了吗，我网上找python版本的Rsa/None/Pkcs1padding，没找到，晚上回去再试试看了

根据这位作者的描述，已经确认是密码的问题https://github.com/gphwxhq/yiban/issues/1#issuecomment-896400204 因此，仅找加密方式是没有用的，重要的是脱壳反编译app找到其中新的公钥

**Comment by Mashiro2000** [comment]
> > > > @Err0rCM `[2]` 我如果没记错的话，应该是password解密失败
> > 
> > 
> > > > 使用的加密算法应当是 `Rsa/None/Pkcs1padding`
> > 
> > 
> > > > _另外 `ct ` 的含义我也想了解一下_
> > 
> > 
> > > 
> > 
> > 
> > > 明白了，看来重构成python必须要找到对应的加密方式，请问师傅的代码可以正确登陆吗？
> > 
> > 
> > > 
> > 
> > 
> > > `ct`的含义其实并不明显，我也不知道具体的含义，记得在之前一个yiban项目看到过，没有什么大的影响似乎。
> > 
> > 
> > 好兄弟，你成功了吗，我网上找python版本的Rsa/None/Pkcs1padding，没找到，晚上回去再试试看了
> 
> 根据这位作者的描述，已经确认是密码的问题[gphwxhq/yiban#1 (comment)](https://github.com/gphwxhq/yiban/issues/1#issuecomment-896400204) 因此，仅找加密方式是没有用的，重要的是脱壳反编译app找到其中新的公钥

准备学反编译，然后发现易班的dex套壳了，老哥有办法反编译吗，腾讯的壳

**Comment by Mashiro2000** [comment]
> > > > @Err0rCM `[2]` 我如果没记错的话，应该是password解密失败
> > 
> > 
> > > > 使用的加密算法应当是 `Rsa/None/Pkcs1padding`
> > 
> > 
> > > > _另外 `ct ` 的含义我也想了解一下_
> > 
> > 
> > > 
> > 
> > 
> > > 明白了，看来重构成python必须要找到对应的加密方式，请问师傅的代码可以正确登陆吗？
> > 
> > 
> > > 
> > 
> > 
> > > `ct`的含义其实并不明显，我也不知道具体的含义，记得在之前一个yiban项目看到过，没有什么大的影响似乎。
> > 
> > 
> > 好兄弟，你成功了吗，我网上找python版本的Rsa/None/Pkcs1padding，没找到，晚上回去再试试看了
> 
> 根据这位作者的描述，已经确认是密码的问题[gphwxhq/yiban#1 (comment)](https://github.com/gphwxhq/yiban/issues/1#issuecomment-896400204) 因此，仅找加密方式是没有用的，重要的是脱壳反编译app找到其中新的公钥

https://blog.csdn.net/ewyherayh/article/details/108950093#comments_17872519

https://segmentfault.com/a/1190000021759690

康康

**Comment by ShirasawaSama** [comment]
@Mashiro2000 @Err0rCM  公钥又更新了吗，我这里还能正常登陆呀

**Comment by Err0rCM** [comment]
> @Mashiro2000 @Err0rCM
> 
> 公钥又更新了吗，但我这里还能正常登陆呀
> 
> 而且现在版本的公钥是使用c/c++写的获取函数，然后使用jni暴露给java使用，并对调用这个函数的上下文进行了校验，单纯反编译apk还不行

如果师傅可以正常登录的话，那应该不是公钥更新的问题，而是python对Rsa/None/Pkcs1padding加密的支持问题，这是我的加密示例
```python
    def encrypt_passwd(self, pwd):
        #密码加密
        PUBLIC_KEY = '''-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA6aTDM8BhCS8O0wlx2KzA
Ajffez4G4A/QSnn1ZDuvLRbKBHm0vVBtBhD03QUnnHXvqigsOOwr4onUeNljegIC
XC9h5exLFidQVB58MBjItMA81YVlZKBY9zth1neHeRTWlFTCx+WasvbS0HuYpF8+
KPl7LJPjtI4XAAOLBntQGnPwCX2Ff/LgwqkZbOrHHkN444iLmViCXxNUDUMUR9bP
A9/I5kwfyZ/mM5m8+IPhSXZ0f2uw1WLov1P4aeKkaaKCf5eL3n7/2vgq7kw2qSmR
AGBZzW45PsjOEvygXFOy2n7AXL9nHogDiMdbe4aY2VT70sl0ccc4uvVOvVBMinOp
d2rEpX0/8YE0dRXxukrM7i+r6lWy1lSKbP+0tQxQHNa/Cjg5W3uU+W9YmNUFc1w/
7QT4SZrnRBEo++Xf9D3YNaOCFZXhy63IpY4eTQCJFQcXdnRbTXEdC3CtWNd7SV/h
mfJYekb3GEV+10xLOvpe/+tCTeCDpFDJP6UuzLXBBADL2oV3D56hYlOlscjBokNU
AYYlWgfwA91NjDsWW9mwapm/eLs4FNyH0JcMFTWH9dnl8B7PCUra/Lg/IVv6HkFE
uCL7hVXGMbw2BZuCIC2VG1ZQ6QD64X8g5zL+HDsusQDbEJV2ZtojalTIjpxMksbR
ZRsH+P3+NNOZOEwUdjJUAx8CAwEAAQ==
-----END PUBLIC KEY-----'''
        cipher = PKCS1_v1_5.new(RSA.importKey(PUBLIC_KEY))
        cipher_text = base64.b64encode(cipher.encrypt(bytes(pwd, encoding="utf8")))
        return parse.quote(cipher_text.decode("utf-8"))
```
加密密码：`123456`
加密后：`wVCcUi98t/yIVYBbfFeNDeqQDH7FV89BBH%2BKKvvvJ/XQIlMH7V1DqBJgyucxLczT5KA8HMn%2B0drtlybt/XasPnENBDUBxE7TfFOyUjOgkAyvcmnvBXVFHrOeExjlk8F3YHzAmivMvg2ouYGbufnKdN8YwalIoc%2BuIovoPdbfWnD8378K9v9JJakQqGqFn80t0pRBgJAOZ0NTS0yPtTt69BEWCywm0TJa%2Bgr/sYaTjNKHOv0C80snYjMVwsfRcBPwov1WqsSUtYat4I4qlklDwgpB0qqd916vIb7YvqhN9VFCxTYuUN5hTo1Hs4q219H6IMIeVR4EUIFH4OI3JD2MLNUtIwvNv830eUh3/kJQwGf2rx/1i1oyfaTaVU6Kapcy8Aa43uxD9KGeD1agjW1U/AesrEYsy264WefsN5w370btB/6OSHOLv5A0DXuVk3TNEGTvHVaZYxlGmS2pjyVKThOvB/AXT2JsKby/zAwCXZNKksZCnRWj8qHvBUd8iOve%2BslxixDhJB5Z9DPLrGKwfRceWQq3u%2BiG0zGHC6ECePVUWiBidndLTOQO0Ay7Jc7TfhneURb4VmmLhRPHDsxIYxjtkDm9uRJymkcXrpIkVNiTSq9SGcDThp9S4xv2Gbg8jti5EvI0ofnXlwTb8YdsSfi38MtTxIDSFQfXzNzoGbY%3D`

**Comment by Err0rCM** [comment]
@Mashiro2000 @ShirasawaSama 
修改了加密的函数如下即可正确登陆
```python
    def encrypt_passwd(self, pwd):
        #密码加密
        PUBLIC_KEY = '''-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA6aTDM8BhCS8O0wlx2KzA
Ajffez4G4A/QSnn1ZDuvLRbKBHm0vVBtBhD03QUnnHXvqigsOOwr4onUeNljegIC
XC9h5exLFidQVB58MBjItMA81YVlZKBY9zth1neHeRTWlFTCx+WasvbS0HuYpF8+
KPl7LJPjtI4XAAOLBntQGnPwCX2Ff/LgwqkZbOrHHkN444iLmViCXxNUDUMUR9bP
A9/I5kwfyZ/mM5m8+IPhSXZ0f2uw1WLov1P4aeKkaaKCf5eL3n7/2vgq7kw2qSmR
AGBZzW45PsjOEvygXFOy2n7AXL9nHogDiMdbe4aY2VT70sl0ccc4uvVOvVBMinOp
d2rEpX0/8YE0dRXxukrM7i+r6lWy1lSKbP+0tQxQHNa/Cjg5W3uU+W9YmNUFc1w/
7QT4SZrnRBEo++Xf9D3YNaOCFZXhy63IpY4eTQCJFQcXdnRbTXEdC3CtWNd7SV/h
mfJYekb3GEV+10xLOvpe/+tCTeCDpFDJP6UuzLXBBADL2oV3D56hYlOlscjBokNU
AYYlWgfwA91NjDsWW9mwapm/eLs4FNyH0JcMFTWH9dnl8B7PCUra/Lg/IVv6HkFE
uCL7hVXGMbw2BZuCIC2VG1ZQ6QD64X8g5zL+HDsusQDbEJV2ZtojalTIjpxMksbR
ZRsH+P3+NNOZOEwUdjJUAx8CAwEAAQ==
-----END PUBLIC KEY-----'''
        cipher = PKCS1_v1_5.new(RSA.importKey(PUBLIC_KEY))
        cipher_text = base64.b64encode(cipher.encrypt(bytes(pwd, encoding="utf8")))
        return cipher_text.decode("utf-8")
```
感谢师傅付出 @ShirasawaSama ，如果师傅 @Mashiro2000 没有其他问题我就关闭issue了
再次感谢师傅们的协助！希望以后有机会我们还能一起研究。

**Comment by Mashiro2000** [comment]
总之，谢谢梁伟玲
